### ISSUE TITLE
Transform re.search to re.compile

### ISSUE THREAD

**Issue by ahivert** [jurismarches/geoconvert#1]
After make some profiling, lot of time is passed on re.search.
We should use re.compile in place of simple re.search to improve some perfs.

**Comment by roxanebellot** [comment]
As I understand, done in version 4.0.0 ([commit](https://github.com/jurismarches/geoconvert/commit/1e391ab2af555fb2f50ac84c96ef80f07882daf2#diff-935f490bccb683c11bdc72b284cdace7f55b4af97a89654f69cf101ed527d0a4))

**Comment by roxanebellot** [comment]
Closing issue
